# Майнор "Интеллектуальный анализ данных", Введение в Анализ данных (ВШЭ)
<H3>Выполнил: Хорин Максим

Задание состоит в том, чтобы дописать в этом ipython notebook тело для всех функций, чтобы они работали так, как указано в формулировке. 

**При решении задач нельзя пользоваться циклами и рекурсией.**

In [1]:
import numpy as np
import pandas as pd

__№1__.(Completed)  Написать функцию, которая берет на вход прямоугольную матрицу $A$ размера m x n и превращает каждый ее столбец в дискретное распределение с помощью применения функции _softmax_:

$\text{softmax}(a_j) = \frac {\exp (a_j)}{\sum_i \exp(a_i)}$, где a --- столбец матрицы $A$.

Таким образом, в матрице, возвращенной функцией, сумма каждого столбца матрицы должна быть равна 1.

In [4]:
m = np.random.randint(2, 6)
n = np.random.randint(2, 6)
A = np.random.randint(0, 3,(m, n))

def compute_softmax(A):
    A = np.exp(A) / np.sum(np.exp(A), axis = 0)
    return A

print('Input:\n', A)
A = compute_softmax(A)
print('Output:\n', A)

#Для проверки
print('Сумма по столбцам:', np.sum(A, axis = 0))    

Input:
 [[2 0 0 1]
 [1 0 1 1]
 [2 2 2 2]]
Output:
 [[ 0.4223188   0.10650698  0.09003057  0.21194156]
 [ 0.1553624   0.10650698  0.24472847  0.21194156]
 [ 0.4223188   0.78698604  0.66524096  0.57611688]]
Сумма по столбцам: [ 1.  1.  1.  1.]


__№2__.(Completed) Напишите функцию, принимающую на вход матрицу X и два массива i и j одинаковой длины n и возвращающую вектор np.array, состоящий из последовательности элементов [X[i[0], j[0]], X[i[1], j[1]], ..., X[i[n-1], j[n-1]]].

In [11]:
#Пример

Example
Input:
X = [[0 1]
 [1 2]]
i =  [0 0] j =  [0 1]
Output:
0 1


In [6]:
n = np.random.randint(3, 5)
X = np.random.randint(0, 11, (n, n))
i = np.random.randint(0, 3, (n))
j = np.random.randint(0, 3,(n))

def choose_elems(X, i, j):
    return np.array(X[i[::],j[::]]) 

print('Matrix:\n', X)
print('Array i:', i)
print('Array j:', j)
print("Output:",choose_elems(X, i, j))

Matrix:
 [[ 9  6  8]
 [ 6  1  2]
 [10  1  5]]
Array i: [1 0 2]
Array j: [0 0 1]
Output: [6 9 1]


__№3__.(Completed) Написать функцию, которая берет на вход матрицу A размера m x n, вектор b длины m и вектор c длины n и возвращает матрицу, составленную из блоков:

$\begin{pmatrix} A & b \\  c^T& 0 \end{pmatrix}$ = 

$\begin{pmatrix} a_{00} & a_{01} & \dots &a_{0,n-1} & b_0 \\ 
a_{10} & a_{11} & \dots &a_{1,n-1} & b_1 \\
 &&\dots& \\
a_{m-1,0} & a_{m-1,1} & \dots &a_{m-1,n-1} & b_{m-1} \\ 
c_0 & c_1 & \dots & c_{n-1 }& 0 \end{pmatrix}$

Будем считать, что матрица A может быть очень большой, поэтому выделять дополнительную память размера, сопоставимого с размером матрицы, нельзя.

In [12]:
#Пример

Example
Input:
A = [[0 1]
 [1 2]]
b =  [8 9] c =  [7 3]
Output:
[[0 1 8]
 [1 2 9]
 [7 3 0]]


In [7]:
# Пример для матрицы (2,2)и векторов (2,) (2,)

m = 2 #np.random.randint(2, 10) # переменная автоматически генерирует размерности
n = 2 #np.random.randint(2, 10) # переменная автоматически генерирует размерности
A = np.random.randint(0, 21, (m, n))
b = np.random.randint(1, 11, (m, ))
c = np.random.randint(1, 11, (n, ))

def construct_matrix(A, b, c):
    b = np.reshape(b, (len(b), 1))
    c = np.reshape(c, (len(c), 1))
    A = np.hstack((A, b))
    zero = np.zeros((1, 1), dtype = int)
    c = np.hstack((c.T, zero))
    A = np.vstack((A, c))
    return A

print('Matrix А:\n', A)
print('Vector b:', b)
print('Vector с:', c)
print('Constructed matrix:\n', construct_matrix(A, b, c))

Matrix А:
 [[15 12]
 [ 5 15]]
Vector b: [2 8]
Vector с: [5 6]
Constructed matrix:
 [[15 12  2]
 [ 5 15  8]
 [ 5  6  0]]


__№4__. Даны две небольшие бинарные матрицы $A$ размера $m \times n$ и $B$ размера $n \times k$. 
Написать функцию, возвращающую матрицу $C$ такую, что

$C_{ij} = \&_{s=1}^n (A_{is} \lor B_{sj})$.

Здесь $\&$ означает логическое умножение (and), а $\lor$ — дизъюнкцию (or).

In [14]:
#Пример

Example
Input:
A = [[False  True]
 [ True False]]
Input:
B = [[ True False]
 [False  True]]
Output:
[[ True False]
 [False  True]]


In [ ]:
def perform_logical_computation(A, B):
    

__№5__.(Completed) Напишите функцию, принимающую на вход np.array размера n и возвращающую матрицу размера n + 1 x n + 1, у которой над главной даигональю стоят элементы массива (остальные элементы должны быть нулевыми). 

In [15]:
#Пример

Example
Input:
[[1 2]]
Output:
[[0 1 0]
 [0 0 2]
 [0 0 0]]


In [8]:
n = np.random.randint(2, 8)
A = np.array(np.random.randint(1,21,(1,n)), dtype = int)

def transform_matrix(A):
    A = A.T * np.eye(n, dtype = int)
    A_changed = np.hstack((np.zeros((n,1), dtype = int), A))
    A = np.vstack((A_changed, np.zeros((1,n+1), dtype = int)))
    return A

print('Source:\n', A)
print('Transformed matrix:\n', transform_matrix(A))

Source:
 [[11 19 19 11 14 11]]
Transformed matrix:
 [[ 0 11  0  0  0  0  0]
 [ 0  0 19  0  0  0  0]
 [ 0  0  0 19  0  0  0]
 [ 0  0  0  0 11  0  0]
 [ 0  0  0  0  0 14  0]
 [ 0  0  0  0  0  0 11]
 [ 0  0  0  0  0  0  0]]


__№6__. Дана матрица объекты-признаки X размера n x m. Посчитать (квадратную) матрицу попарных корреляций между признаками C:

$C_{ij} = cor_{ij} = \frac {cov_{ij}}{\sqrt{cov_{ii}cov_{jj}}}$ 

$cov_{ij} = cov(X_i, X_j), \quad i,j = 0, \dots, m-1.$

$cov(\{x_0, \dots, x_{n-1}\}, \{y_0, \dots, y_{n-1}\}) = \frac 1 {n-1} \sum_{i=0} ^ {n-1} (x_i-\bar x) (y_i - \bar y)$.

$\bar x = mean(\{x_0, \dots, x_{n-1}\}) = \frac 1 n \sum_{i=0} ^ {n-1} x_i$

Нельзя использовать функции np.cov, np.corrcoef, np.correlate (их можно использовать для проверки правильности ответа)


In [ ]:
def compute_corr_matrix(X):
    

__№7__.(Completed) Дан массив X (размерность неизвестна). Заменить все элементы, кратные 3, которые больше 0 и меньше 100, на среднее значение по массиву.

In [19]:
#Пример

Example
Input:
[[14 11 10  0 12]
 [ 9  4 13  8  3]
 [ 6 14 13  5  5]
 [ 8  1  6  7 12]]
Output:
[[14 11 10  0  8]
 [ 8  4 13  8  8]
 [ 8 14 13  5  5]
 [ 8  1  8  7  8]]


In [9]:
import pandas as pd
n = np.random.randint(1,6)
m = np.random.randint(1,6)
X = np.random.randint(0,50,(n,m))

def ChangeMatrix(X):
    X[(X % 3 == 0) & np.logical_and( X > 0, X < 100)] = np.mean(X)
    return X

print('Input:\n', X)
print('Output:\n', ChangeMatrix(X))

Input:
 [[25 31 27 47 35]
 [ 8  9 16 14 17]
 [36 41 39 17 11]]
Output:
 [[25 31 24 47 35]
 [ 8 24 16 14 17]
 [24 41 24 17 11]]


Для выполнения заданий по pandas понадобится файл _countries.csv_: [https://goo.gl/AQqxaR](https://goo.gl/AQqxaR) --- тут его нужно скачать! Чтобы загрузить файл в jupiter, на странице с ноутбуками нажмите Upload, найдите на компьютере файл, снов анажмите upload.

__№8__.(Completed) Напишите функцию, которая берет на вход датафрейм pandas со считанными данными и возвращает ответ на следующий вопрос (строка).

Найдите страну, у которой наибольшее ВВП среди стран площадью меньше 200 или население меньше 10000 (или — не исключающее).

In [48]:
df = pd.read_csv('countries.csv', sep=';')

def find_country(df):
    sample = df.loc[(df["Area(sq km)"] < 200) | (df["Population"] < 10000)]
    maxGDP = np.max(sample['GDP'])
    country = sample.Country[sample.GDP == maxGDP]
    return str(country).split('\n')[0].split('    ')[1]

print('Страна, у которой наибольшее ВВП среди стран площадью меньше 200 или населением меньше 10000:', find_country(df))

Страна, у которой наибольшее ВВП среди стран площадью меньше 200 или населением меньше 10000: Macau


__№9__.(Completed)  Напишите функцию, которая берет на вход датафрейм pandas и возвращает датафрейм, в котором все пропуски заменены на среднее значение по столбцу без пропусков. 

_Подсказка_: используйте функцию pandas.fillna()

In [56]:
df = pd.read_csv('countries.csv', sep = ';')

def fill_na(df):
    df = df.fillna(df.dropna().mean())
    return df

fill_na(df)

Country  Area(sq km)  \
0                    Afghanistan       647500   
1                       Akrotiri          123   
2                        Albania        28748   
3                        Algeria      2381740   
4                 American Samoa          199   
5                        Andorra          468   
6                         Angola      1246700   
7                       Anguilla          102   
8                     Antarctica     14000000   
9            Antigua and Barbuda          443   
10                     Argentina      2766890   
11                       Armenia        29800   
12                         Aruba          193   
13   Ashmore and Cartier Islands            5   
14                     Australia      7686850   
15                       Austria        83870   
16                    Azerbaijan        86600   
17                   Bahamas The        13940   
18                       Bahrain          665   
19                  Baker Island            1   
20                    Bangladesh       144000   
21                      Barbados          431   
22               Bassas da India            0   
23                       Belarus       207600   
24                       Belgium        30528   
25                        Belize        22966   
26                         Benin       112620   
27                       Bermuda           53   
28                        Bhutan        47000   
29                       Bolivia      1098580   
..                           ...          ...   
233                     Tanzania       945087   
234                     Thailand       514000   
235                         Togo        56785   
236                      Tokelau           10   
237                        Tonga          748   
238          Trinidad and Tobago         5128   
239              Tromelin Island            1   
240                      Tunisia       163610   
241                       Turkey       780580   
242                 Turkmenistan       488100   
243     Turks and Caicos Islands          430   
244                       Tuvalu           26   
245                       Uganda       236040   
246                      Ukraine       603700   
247         United Arab Emirates        82880   
248               United Kingdom       244820   
249                United States      9631418   
250                      Uruguay       176220   
251                   Uzbekistan       447400   
252                      Vanuatu        12200   
253                    Venezuela       912050   
254                      Vietnam       329560   
255               Virgin Islands          352   
256                  Wake Island            7   
257            Wallis and Futuna          274   
258                    West Bank         5860   
259               Western Sahara       266000   
260                        Yemen       527970   
261                       Zambia       752614   
262                     Zimbabwe       390580   

     Birth rate(births/1000 population)  Current account balance  \
0                             47.020000            -4.152212e+09   
1                             13.932778            -4.152212e+09   
2                             15.080000            -5.040000e+08   
3                             17.130000             1.190000e+10   
4                             23.130000            -4.152212e+09   
5                              9.000000            -4.152212e+09   
6                             44.640000            -3.788000e+07   
7                             14.260000            -4.152212e+09   
8                             13.932778            -4.152212e+09   
9                             17.260000            -4.152212e+09   
10                            16.900000             5.473000e+09   
11                            11.760000            -2.404000e+08   
12                            11.260000            -4.152212e+09   
13                            13.9

__№10__.(Completed)  Напишите функцию, которая берет на вход датафрейм pandas и число и возвращает ответ на вопрос (строка):

В какой стране ВВП (GDP) наиболее близок к указанной величине?

In [47]:
df = pd.read_csv('countries.csv', sep=';')

def compare_GDP(df, gdp):
    df.insert(loc = 10, column = "GDP_diff", value = np.abs(df.GDP - gdp))
    return str(df.Country[df.GDP_diff == np.min(df.GDP_diff)]).split('\n')[0].split('    ')[1]

print("Страна, в которой ВВП наиболее близок к указанной величине:", compare_GDP(df, 39396030702))

Страна, в которой ВВП наиболее близок к указанной величине: Uganda


__№11__. __(Дополнительный).(Completed) За выполнение этого задания можно получить +1 балл к общей сумме баллов (к 10)!__

Напишите функцию, которая берет на вход датафрейм pandas со считанными данными и возвращает датафрейм с двумя колонками: буква алфавита и значение ВВП, усреднённое по всем странам, начинающимся с данной буквы.

Для решения задачи может понадобиться функция pandas.groupby, которую вы не успели пройти на семинаре. Поэтому задача и дополнительная.

In [19]:
df = pd.read_csv('countries.csv', sep=';')

def compute_means_by_letters(df):
    condition = [df.loc[df['Country'].str.startswith(chr(x))].mean()['GDP'] for x in range(ord('A'), ord('Z') + 1)]
    new_df = pd.DataFrame({'Letter' : [chr(x) for x in range(ord('A'), ord('Z') + 1)], 'GDP' : condition})
    return new_df.dropna() #Теперь обрабатывает NaN

compute_means_by_letters(df)

GDP Letter
0   1.195994e+11      A
1   1.210610e+11      B
2   4.591804e+11      C
3   5.777075e+10      D
4   5.975925e+10      E
5   2.715113e+11      F
6   1.621848e+11      G
7   1.036600e+11      H
8   8.283341e+11      I
9   9.463075e+11      J
10  1.665191e+11      K
11  1.958222e+10      L
12  6.833354e+10      M
13  7.424858e+10      N
14  3.809000e+10      O
15  1.716514e+11      P
16  1.949000e+10      Q
17  3.986250e+11      R
18  1.025396e+11      S
19  1.354214e+11      T
20  2.004431e+12      U
21  9.387000e+10      V
22  9.300000e+08      W
24  1.625000e+10      Y
25  1.688950e+10      Z